version: '3'
services:
  airplay:
    image: issogr/airplay-audio
    restart: always
    network_mode: host
    devices:
      - /dev/snd
    environment:
      - AIRPLAY_NAME=NicoAudioReceiver

  pulseaudio-bluetooth:
    restart: always
    image: cdauth/a2dp-server
    privileged: true
    devices:
      - /dev/bus/usb
      - /dev/snd
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/locialtime:ro
      - ./bluetooth:/var/lib/bluetooth
    environment:
      - PIN=000000
      - NAME=NicoAudioReceiver
      - DEVICE=8C:88:2B:60:3D:15
      - DEVICE_PIN=0000