version: '3'
services:
  airplay:
    build: ./airplay
    network_mode: host
    restart: unless-stopped
    devices:
      - "/dev/snd" # ALSA device
    environment:
       - AIRPLAY_NAME=${DEVICE_NAME}

  pulseaudio-bluetooth:
    restart: always
    image: cdauth/a2dp-server
    privileged: true
    devices:
      - /dev/bus/usb
      - /dev/snd
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/locialtime:ro
      - ./.storage/bluetooth:/var/lib/bluetooth
    environment:
      - NAME=${DEVICE_NAME}
      - DEVICE=${BLUETOOTH_MAC}